// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package homepage_templ

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Setup() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>College Assist</title><link id=\"theme\" rel=\"stylesheet\" href=\"../css/homepage_styles.css\"><script type=\"module\" src=\"https://cdn.jsdelivr.net/gh/starfederation/datastar@v1.0.0/bundles/datastar.js\"></script></head><body><header class=\"app-header\"><div class=\"header-left\"><a href=\"/\" class=\"brand-link\"><div class=\"brand-icon\"><svg fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" stroke-width=\"2\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M13 10V3L4 14h7v7l9-11h-7z\"></path></svg></div><span class=\"brand-text\">College Assist</span></a></div><nav class=\"main-nav\"><a href=\"#features\">Features</a> <a href=\"#testimonials\">Testimonials</a></nav><div class=\"header-right\"><a class=\"btn btn-ghost\" id=\"signin-btn\" href=\"/login\">Sign In</a> <a class=\"btn btn-ghost\" id=\"signup-btn\" href=\"/signup\">Get Started Free</a></div></header><main><section id=\"promise-to-users\"><div id=\"prom-title-container\"><h1 id=\"prom-title\">Stop Planning, Start Learning</h1><h2 id=\"prom-subtitle\">The all-in-one AI study assistant that turns your syllabus into a master schedule, generates custom practice quizzes, and automates your entire study routine.</h2></div></section></main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
